# Generated by Django 6.0.3 on 2026-04-01 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_remove_paciente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bot', models.CharField(default='Assistente', max_length=100)),
                ('usar_ia', models.BooleanField(default=False)),
                ('limite_mensagens', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('resposta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConversaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('resposta', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
