# Generated by Django 6.0.3 on 2026-04-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversawhatsapp',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversawhatsapp',
            name='quer_agendar',
            field=models.BooleanField(default=False),
        ),
    ]
