# Generated by Django 6.0.3 on 2026-03-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_consulta_criado_em_alter_consulta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
