# Generated by Django 6.0.3 on 2026-04-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_conversawhatsapp_atendido_and_more'),
        ('usuarios', '0002_remove_paciente_clinica_remove_perfil_clinica_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoIA',
        ),
        migrations.AddField(
            model_name='conversawhatsapp',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.clinica'),
            preserve_default=False,
        ),
    ]
