# Generated by Django 6.0.3 on 2026-03-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_consulta_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='duracao',
            field=models.IntegerField(default=30),
        ),
    ]
