# Generated by Django 6.0.3 on 2026-03-22 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_consulta_duracao'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('bloqueio', 'Bloqueio')], default='consulta', max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
    ]
