# Generated by Django 6.0.3 on 2026-03-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_consulta_tipo_alter_consulta_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='lembrete_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('bloqueio', 'Bloqueio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
