# Generated by Django 6.0.3 on 2026-03-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_consulta_lembrete_enviado_alter_consulta_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('etapa', models.CharField(default='inicio', max_length=50)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.CharField(blank=True, max_length=20, null=True)),
                ('horario', models.CharField(blank=True, max_length=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
