# Generated by Django 6.0.3 on 2026-03-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ia', models.CharField(default='Sofia', max_length=50)),
                ('tom', models.TextField(default='Responda de forma educada, profissional e acolhedora.')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=100)),
                ('resposta', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.RemoveField(
            model_name='conversawhatsapp',
            name='data',
        ),
        migrations.RemoveField(
            model_name='conversawhatsapp',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='conversawhatsapp',
            name='nome',
        ),
    ]
