# Generated by Django 6.0.3 on 2026-03-30 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_paciente_criado_em_alter_paciente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='paciente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
