# Generated by Django 6.0.3 on 2026-04-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_remove_paciente_data_nascimento_and_more'),
        ('usuarios', '0002_remove_paciente_clinica_remove_perfil_clinica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.clinica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
