# Generated by Django 6.0.3 on 2026-04-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='email',
        ),
        migrations.AddField(
            model_name='clinica',
            name='cor_primaria',
            field=models.CharField(default='#25D366', max_length=20),
        ),
        migrations.AddField(
            model_name='clinica',
            name='nome_ia',
            field=models.CharField(default='Assistente', max_length=100),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
