# Generated by Django 6.0.3 on 2026-04-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_clinica_cor_primaria_remove_clinica_nome_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='cor_primaria',
            field=models.CharField(default='#e91e63', max_length=20),
        ),
        migrations.AddField(
            model_name='clinica',
            name='cor_secundaria',
            field=models.CharField(default='#d4af37', max_length=20),
        ),
    ]
